/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hexadon;

/**
 *
 * @author S_340
 */
public class DB extends javax.swing.JFrame {

    /**
     * Creates new form DB
     */
    public DB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText("Turkish");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 160, 110, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel3.setText("10");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 156, 41, 10);

        jLabel4.setText("Rp. 35.000");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(230, 170, 100, 20);

        jLabel5.setText("Red Velvet");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 210, 75, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel6.setText("10");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(460, 206, 12, 10);

        jLabel7.setText("Rp. 35.000");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(460, 220, 90, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel9.setText("10");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(230, 256, 20, 14);

        jLabel8.setText("Lotus");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 264, 120, 20);

        jLabel10.setText("Rp. 35.000");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(230, 270, 90, 20);

        jLabel11.setText("Chocolate");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(280, 310, 110, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel12.setText("10");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(460, 306, 12, 10);

        jLabel13.setText("Rp. 35.000");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(460, 320, 80, 20);

        jLabel14.setText("Cadburry");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(50, 360, 110, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel15.setText("10");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(230, 356, 12, 10);

        jLabel16.setText("Rp. 35.000");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(230, 370, 80, 20);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        getContentPane().add(jSpinner1);
        jSpinner1.setBounds(170, 160, 37, 26);

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        getContentPane().add(jSpinner2);
        jSpinner2.setBounds(400, 210, 37, 26);

        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        getContentPane().add(jSpinner3);
        jSpinner3.setBounds(180, 260, 37, 26);

        jSpinner4.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        getContentPane().add(jSpinner4);
        jSpinner4.setBounds(410, 310, 37, 26);

        jSpinner5.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        getContentPane().add(jSpinner5);
        jSpinner5.setBounds(170, 360, 37, 26);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/BG_DB.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    // End of variables declaration//GEN-END:variables
}
