/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hexadon;

/**
 *
 * @author S_340
 */
public class Donat extends javax.swing.JFrame {

    /**
     * Creates new form Donat
     */
    public Donat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Donat Gula");
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 100, 220, 40);

        jLabel2.setText("10");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(390, 100, 14, 16);

        jLabel3.setText("Rp. 2.000");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 120, 55, 16);

        jButton2.setText("Donat Cokelat");
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 150, 220, 40);

        jLabel4.setText("10");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 150, 14, 16);

        jLabel5.setText("Rp. 2.500");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 170, 60, 16);

        jButton3.setText("Donat Cokelat Putih");
        getContentPane().add(jButton3);
        jButton3.setBounds(310, 150, 210, 40);

        jLabel6.setText("10");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(530, 150, 14, 16);

        jLabel7.setText("Rp. 2.500");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(530, 170, 55, 16);

        jButton4.setText("Donat Matcha");
        getContentPane().add(jButton4);
        jButton4.setBounds(10, 200, 220, 40);

        jLabel8.setText("10");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(240, 200, 14, 16);

        jLabel9.setText("Rp. 2.500");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(240, 220, 60, 16);

        jButton5.setText("Donat Tiramisu");
        getContentPane().add(jButton5);
        jButton5.setBounds(310, 200, 210, 40);

        jLabel10.setText("10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(530, 200, 14, 16);

        jLabel11.setText("Rp. 2.500");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(530, 220, 60, 16);

        jButton6.setText("Donat Strawberry");
        getContentPane().add(jButton6);
        jButton6.setBounds(10, 250, 220, 40);

        jLabel12.setText("10");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(240, 250, 14, 16);

        jLabel13.setText("Rp. 2.500");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(240, 270, 60, 16);

        jButton7.setText("Donat Blueberry");
        getContentPane().add(jButton7);
        jButton7.setBounds(310, 250, 210, 40);

        jLabel14.setText("10");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(530, 250, 14, 16);

        jLabel15.setText("Rp. 2.500");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(530, 270, 60, 16);

        jButton8.setText("Donat Cappuchino");
        getContentPane().add(jButton8);
        jButton8.setBounds(10, 300, 220, 40);

        jLabel16.setText("10");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(240, 300, 14, 16);

        jLabel17.setText("Rp. 2.500");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(240, 320, 55, 16);

        jButton9.setText("Donat Bomboloni Isi Cokelat");
        getContentPane().add(jButton9);
        jButton9.setBounds(310, 300, 210, 40);

        jLabel18.setText("10");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(530, 300, 14, 16);

        jLabel19.setText("Rp. 3.000");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(530, 320, 60, 16);

        jButton10.setText("Donat Bomboloni Isi Strawberry");
        getContentPane().add(jButton10);
        jButton10.setBounds(10, 360, 220, 40);

        jLabel20.setText("10");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(240, 360, 14, 16);

        jLabel21.setText("Rp. 3.000");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(240, 380, 60, 16);

        jButton11.setText("Donat Bomboloni Isi Blueberry");
        getContentPane().add(jButton11);
        jButton11.setBounds(310, 360, 210, 40);

        jLabel22.setText("10");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(530, 360, 14, 16);

        jLabel23.setText("Rp. 3.000");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(530, 380, 55, 16);

        jButton12.setText("Donat Selai Strawberry");
        getContentPane().add(jButton12);
        jButton12.setBounds(10, 420, 220, 40);

        jLabel24.setText("10");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(240, 420, 14, 16);

        jLabel25.setText("Rp. 3.000");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(240, 440, 60, 16);

        jButton13.setText("Donat Selai Blueberry");
        getContentPane().add(jButton13);
        jButton13.setBounds(310, 420, 210, 40);

        jLabel26.setText("10");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(530, 420, 14, 16);

        jLabel27.setText("Rp. 3.000");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(530, 440, 60, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/BG_Donat.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Donat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Donat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Donat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Donat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Donat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
