/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hexadon;

/**
 *
 * @author S_340
 */
public class Transaksi extends javax.swing.JFrame {

    

    /**
     * Creates new form Transaksi
     */
    public Transaksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldTotal = new javax.swing.JTextField();
        fieldUangUser = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelKembalian = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText("Total");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 140, 36, 20);

        jLabel3.setText("Rp.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 140, 24, 20);

        jLabel5.setText("Tunai");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 180, 40, 20);

        fieldTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTotalActionPerformed(evt);
            }
        });
        getContentPane().add(fieldTotal);
        fieldTotal.setBounds(220, 140, 110, 26);

        fieldUangUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUangUserActionPerformed(evt);
            }
        });
        getContentPane().add(fieldUangUser);
        fieldUangUser.setBounds(220, 180, 110, 26);

        jLabel6.setText("Rp.");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 180, 30, 20);

        jLabel7.setText("Kembalian");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 230, 73, 20);

        labelKembalian.setText("Rp.");
        getContentPane().add(labelKembalian);
        labelKembalian.setBounds(190, 230, 140, 20);

        jLabel9.setText(" ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(360, 230, 5, 20);

        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 130, 130, 70);

        jLabel10.setText("Feedback");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(80, 360, 70, 20);

        jTextField2.setText(" ");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(190, 360, 330, 100);

        jLabel11.setText(" ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(190, 270, 320, 20);

        jLabel12.setText(" ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(190, 310, 330, 20);

        jButton2.setText("Cetak Bon");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 490, 180, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/BG_Transaksi.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldUangUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUangUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUangUserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int kembali = Integer.parseInt(fieldUangUser.getText()) - Integer.parseInt(fieldTotal.getText());
        labelKembalian.setText("Rp. " + kembali);
        
        if(kembali < 0) {
            jLabel11.setText("Maaf, uang yang Anda masukkan kurang !");
            jLabel12.setText("Mohon input minimal senilai dengan nilai total !");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Bon bon = new Bon();
        bon.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fieldTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTotalActionPerformed
        // TODO add your handling code here:
        Donat don = new Donat();
        int total = don.getTotalHarga();
        fieldTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_fieldTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldTotal;
    private javax.swing.JTextField fieldUangUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel labelKembalian;
    // End of variables declaration//GEN-END:variables
}
